server:
  port: 9090

spring:
  application:
    name: EurekaService2

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka,http://peer2:8762/eureka